Downgrade build-tools version to 33.0.2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,12 +36,12 @@ jobs:
           mv cmdline-tools latest
           export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
           yes | sdkmanager --licenses
-          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"
-          ls -l $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl || (echo "::error::AIDL not found!" && exit 1)
+          sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-34"
+          ls -l $ANDROID_SDK_ROOT/build-tools/33.0.2/aidl || (echo "::error::AIDL not found!" && exit 1)
 
       - name: Build Full Kivy APK
         run: |
-          export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH"
+          export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH"
           buildozer -v android debug
 
       - name: Upload APK
